sudo: required
services: 
  - docker

before_install:
 - docker build -t hasiqbal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hasiqbal/react-test npm run test

after_sucess:
  - docker build -t hasiqbal/multi-client ./client 
  - docker build -t hasiqbal/multi-nginx ./nginx
  - docker build -t hasiqbal/multi-server ./server
  - docker build -t hasiqbal/mult-worker ./worker

  # login to docker cli 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKE_ID" --password-stdin
  - docker push hasiqbal/multi-client
  - docker push hasiqbal/multi-nginx 
  - docker push hasiqbal/multi-server
  - docker push hasiqbal/mult-worker
